import VueRouter from 'vue-router'

const routes = [{
    path: '/',
    component: require('../views/component/index'),
    children: [{
        path: '/',
        component: require('../views/component/install')
    }, {
        path: 'install',
        component: require('../views/component/install')
    }, {
        path: 'i18n',
        component: require('../views/component/i18n')
    }, {
        path: 'log',
        component: require('../views/component/log')
    }, {
        path: 'play',
        component: require('../views/component/play')
    }, {
        path: 'layout',
        component: require('../views/component/layout')
    }, {
        path: 'button',
        component: require('../views/component/button')
    }, {
        path: 'icon',
        component: require('../views/component/icon')
    }, {
        path: 'tab',
        component: require('../views/component/tab')
    }, {
        path: 'table',
        component: require('../views/component/table')
    }, {
        path: 'checkbox',
        component: require('../views/component/checkbox')
    }, {
        path: 'zoom',
        component: require('../views/component/zoom')
    }, {
        path: 'upload',
        component: require('../views/component/upload')
    }, {
        path: 'toast',
        component: require('../views/component/toast')
    }, {
        path: 'tree',
        component: require('../views/component/tree')
    }, {
        path: 'tooltip',
        component: require('../views/component/tooltip')
    }, {
        path: 'step',
        component: require('../views/component/step')
    }, {
        path: 'message',
        component: require('../views/component/message')
    }, {
        path: 'modal',
        component: require('../views/component/modal')
    }, {
        path: 'loading',
        component: require('../views/component/loading')
    }, {
        path: 'switch',
        component: require('../views/component/switch')
    }, {
        path: 'input',
        component: require('../views/component/input')
    }, {
        path: 'select',
        component: require('../views/component/select')
    }, {
        path: 'radio',
        component: require('../views/component/radio')
    }, {
        path: 'datePicker',
        component: require('../views/component/datePicker')
    }, {
        path: 'form',
        component: require('../views/component/form')
    }, {
        path: 'carousel',
        component: require('../views/component/carousel')
    }, {
        path: 'panel',
        component: require('../views/component/panel')
    }, {
        path: 'pagination',
        component: require('../views/component/pagination')
    }, {
        path: 'menu',
        component: require('../views/component/menu')
    }, {
        path: 'affix',
        component: require('../views/component/affix')
    }, {
        path: 'backtop',
        component: require('../views/component/backTop')
    }, {
        path: 'draggable',
        component: require('../views/component/draggable')
    }, {
        path: 'processCircle',
        component: require('../views/component/processCircle')
    }, {
        path: 'dropdown',
        component: require('../views/component/dropdown')
    }, {
        path: 'contextmenu',
        component: require('../views/component/contextmenu')
    }, {
        path: 'split',
        component: require('../views/component/split')
    }]
}];

export default new VueRouter({
    routes: routes
});